import { EnTopicData, RuTopicData, TitleTopic } from '../model/types';

export const TOPICS: TitleTopic[] = ['business', 'it', 'art', 'science', 'finance', 'marketing'];

export const RU_TOPIC_DATA: Record<TitleTopic, RuTopicData> = {
  business: {
    subjects: [
      {
        nom: 'бизнес',
        gen: 'бизнеса',
        acc: 'бизнес',
        instr: 'бизнесом',
        prep: 'бизнесе',
        withInstr: 'с бизнесом',
      },
      {
        nom: 'компания',
        gen: 'компании',
        acc: 'компанию',
        instr: 'компанией',
        prep: 'компании',
        withInstr: 'с компанией',
      },
      {
        nom: 'рынок',
        gen: 'рынка',
        acc: 'рынок',
        instr: 'рынком',
        prep: 'рынке',
        withInstr: 'с рынком',
      },
      {
        nom: 'стратегия',
        gen: 'стратегии',
        acc: 'стратегию',
        instr: 'стратегией',
        prep: 'стратегии',
        withInstr: 'со стратегией',
      },
      {
        nom: 'команда',
        gen: 'команды',
        acc: 'команду',
        instr: 'командой',
        prep: 'команде',
        withInstr: 'с командой',
      },
    ],
    contexts: ['анализ рынка', 'обратная связь', 'данные о клиентах', 'оценка спроса', 'картина процессов'],
    results: ['прибыль', 'устойчивость', 'рост', 'качество решений', 'скорость развития'],
    problems: [
      'потери фокуса',
      'неясной стратегии',
      'лишней бюрократии',
      'слабой коммуникации',
      'разрыва между планом и результатом',
    ],
    processes: ['работе команды', 'управлении процессами', 'планировании', 'развитии компании', 'принятии решений'],
    tools: ['аналитика', 'системный подход', 'прозрачная коммуникация', 'планирование', 'приоритизация'],
  },

  it: {
    subjects: [
      {
        nom: 'платформа',
        gen: 'платформы',
        acc: 'платформу',
        instr: 'платформой',
        prep: 'платформе',
        withInstr: 'с платформой',
      },
      {
        nom: 'интерфейс',
        gen: 'интерфейса',
        acc: 'интерфейс',
        instr: 'интерфейсом',
        prep: 'интерфейсе',
        withInstr: 'с интерфейсом',
      },
      {
        nom: 'сервис',
        gen: 'сервиса',
        acc: 'сервис',
        instr: 'сервисом',
        prep: 'сервисе',
        withInstr: 'с сервисом',
      },
      {
        nom: 'продукт',
        gen: 'продукта',
        acc: 'продукт',
        instr: 'продуктом',
        prep: 'продукте',
        withInstr: 'с продуктом',
      },
      {
        nom: 'приложение',
        gen: 'приложения',
        acc: 'приложение',
        instr: 'приложением',
        prep: 'приложении',
        withInstr: 'с приложением',
      },
      {
        nom: 'архитектура',
        gen: 'архитектуры',
        acc: 'архитектуру',
        instr: 'архитектурой',
        prep: 'архитектуре',
        withInstr: 'с архитектурой',
      },
    ],
    contexts: [
      'пользовательский опыт',
      'данные интерфейса',
      'продуктовая аналитика',
      'техническая картина',
      'обратная связь пользователей',
    ],
    results: ['стабильность', 'производительность', 'удобство', 'качество продукта', 'скорость разработки'],
    problems: [
      'технического долга',
      'сложной навигации',
      'нестабильной логики',
      'лишней сложности',
      'плохой обратной связи',
    ],
    processes: [
      'разработке',
      'проектировании интерфейса',
      'тестировании',
      'улучшении продукта',
      'работе с архитектурой',
    ],
    tools: ['типизация', 'автоматизация', 'дизайн-система', 'аналитика', 'код-ревью'],
  },

  art: {
    subjects: [
      {
        nom: 'выставка',
        gen: 'выставки',
        acc: 'выставку',
        instr: 'выставкой',
        prep: 'выставке',
        withInstr: 'с выставкой',
      },
      {
        nom: 'галерея',
        gen: 'галереи',
        acc: 'галерею',
        instr: 'галереей',
        prep: 'галерее',
        withInstr: 'с галереей',
      },
      {
        nom: 'визуальный стиль',
        gen: 'визуального стиля',
        acc: 'визуальный стиль',
        instr: 'визуальным стилем',
        prep: 'визуальном стиле',
        withInstr: 'с визуальным стилем',
      },
      {
        nom: 'творческий проект',
        gen: 'творческого проекта',
        acc: 'творческий проект',
        instr: 'творческим проектом',
        prep: 'творческом проекте',
        withInstr: 'с творческим проектом',
      },
      {
        nom: 'композиция',
        gen: 'композиции',
        acc: 'композицию',
        instr: 'композицией',
        prep: 'композиции',
        withInstr: 'с композицией',
      },
      {
        nom: 'арт-объект',
        gen: 'арт-объекта',
        acc: 'арт-объект',
        instr: 'арт-объектом',
        prep: 'арт-объекте',
        withInstr: 'с арт-объектом',
      },
    ],
    contexts: [
      'визуальный анализ',
      'реакция аудитории',
      'творческий процесс',
      'пространство экспозиции',
      'работа с образом',
    ],
    results: ['вовлеченность', 'выразительность', 'интерес зрителей', 'целостность образа', 'эмоциональный эффект'],
    problems: [
      'визуального шума',
      'слабой идеи',
      'потери внимания',
      'неясной подачи',
      'разрыва между формой и смыслом',
    ],
    processes: [
      'работе с формой',
      'создании образа',
      'подготовке экспозиции',
      'поиске выразительности',
      'выстраивании композиции',
    ],
    tools: ['композиция', 'свет', 'цвет', 'пространство', 'ритм'],
  },

  science: {
    subjects: [
      {
        nom: 'исследование',
        gen: 'исследования',
        acc: 'исследование',
        instr: 'исследованием',
        prep: 'исследовании',
        withInstr: 'с исследованием',
      },
      {
        nom: 'гипотеза',
        gen: 'гипотезы',
        acc: 'гипотезу',
        instr: 'гипотезой',
        prep: 'гипотезе',
        withInstr: 'с гипотезой',
      },
      {
        nom: 'эксперимент',
        gen: 'эксперимента',
        acc: 'эксперимент',
        instr: 'экспериментом',
        prep: 'эксперименте',
        withInstr: 'с экспериментом',
      },
      {
        nom: 'модель',
        gen: 'модели',
        acc: 'модель',
        instr: 'моделью',
        prep: 'модели',
        withInstr: 'с моделью',
      },
      {
        nom: 'методика',
        gen: 'методики',
        acc: 'методику',
        instr: 'методикой',
        prep: 'методике',
        withInstr: 'с методикой',
      },
    ],
    contexts: [
      'анализ данных',
      'результаты эксперимента',
      'научная методика',
      'проверка гипотезы',
      'сравнение моделей',
    ],
    results: ['точность', 'достоверность', 'повторяемость', 'качество вывода', 'ясность результата'],
    problems: ['ошибки измерений', 'смещения данных', 'неполной выборки', 'слабой гипотезы', 'неясной методики'],
    processes: [
      'анализе данных',
      'проверке гипотезы',
      'проведении эксперимента',
      'интерпретации результатов',
      'построении модели',
    ],
    tools: ['статистика', 'моделирование', 'сравнительный анализ', 'эксперимент', 'визуализация данных'],
  },

  finance: {
    subjects: [
      {
        nom: 'бюджет',
        gen: 'бюджета',
        acc: 'бюджет',
        instr: 'бюджетом',
        prep: 'бюджете',
        withInstr: 'с бюджетом',
      },
      {
        nom: 'финансовая модель',
        gen: 'финансовой модели',
        acc: 'финансовую модель',
        instr: 'финансовой моделью',
        prep: 'финансовой модели',
        withInstr: 'с финансовой моделью',
      },
      {
        nom: 'отчетность',
        gen: 'отчетности',
        acc: 'отчетность',
        instr: 'отчетностью',
        prep: 'отчетности',
        withInstr: 'с отчетностью',
      },
      {
        nom: 'денежный поток',
        gen: 'денежного потока',
        acc: 'денежный поток',
        instr: 'денежным потоком',
        prep: 'денежном потоке',
        withInstr: 'с денежным потоком',
      },
      {
        nom: 'инвестиционный портфель',
        gen: 'инвестиционного портфеля',
        acc: 'инвестиционный портфель',
        instr: 'инвестиционным портфелем',
        prep: 'инвестиционном портфеле',
        withInstr: 'с инвестиционным портфелем',
      },
    ],
    contexts: ['анализ расходов', 'финансовый прогноз', 'структура затрат', 'движение денег', 'оценка рисков'],
    results: ['доходность', 'прозрачность', 'контроль расходов', 'финансовую устойчивость', 'точность прогноза'],
    problems: ['кассового разрыва', 'неясной отчетности', 'роста затрат', 'ошибок планирования', 'потери контроля'],
    processes: [
      'бюджетировании',
      'финансовом планировании',
      'анализе расходов',
      'управлении рисками',
      'подготовке отчетности',
    ],
    tools: ['прогнозирование', 'финансовая аналитика', 'учет расходов', 'планирование', 'контроль показателей'],
  },

  marketing: {
    subjects: [
      {
        nom: 'кампания',
        gen: 'кампании',
        acc: 'кампанию',
        instr: 'кампанией',
        prep: 'кампании',
        withInstr: 'с кампанией',
      },
      {
        nom: 'бренд',
        gen: 'бренда',
        acc: 'бренд',
        instr: 'брендом',
        prep: 'бренде',
        withInstr: 'с брендом',
      },
      {
        nom: 'аудитория',
        gen: 'аудитории',
        acc: 'аудиторию',
        instr: 'аудиторией',
        prep: 'аудитории',
        withInstr: 'с аудиторией',
      },
      {
        nom: 'воронка продаж',
        gen: 'воронки продаж',
        acc: 'воронку продаж',
        instr: 'воронкой продаж',
        prep: 'воронке продаж',
        withInstr: 'с воронкой продаж',
      },
      {
        nom: 'контент-стратегия',
        gen: 'контент-стратегии',
        acc: 'контент-стратегию',
        instr: 'контент-стратегией',
        prep: 'контент-стратегии',
        withInstr: 'с контент-стратегией',
      },
    ],
    contexts: ['анализ аудитории', 'поведение клиентов', 'данные кампании', 'карта касаний', 'оценка спроса'],
    results: ['конверсию', 'узнаваемость', 'лояльность', 'качество лидов', 'эффективность коммуникации'],
    problems: [
      'размытого позиционирования',
      'низкой конверсии',
      'потери внимания',
      'слабого сообщения',
      'неверного сегмента',
    ],
    processes: ['запуске кампании', 'работе с аудиторией', 'создании контента', 'настройке воронки', 'развитии бренда'],
    tools: ['сегментация', 'аналитика', 'контент', 'позиционирование', 'тестирование гипотез'],
  },
};

export const EN_TOPIC_DATA: Record<TitleTopic, EnTopicData> = {
  business: {
    subjects: ['business', 'company', 'market strategy', 'team workflow', 'growth strategy', 'business process'],
    contexts: ['market analysis', 'customer feedback', 'business data', 'demand analysis', 'process overview'],
    results: ['profitability', 'stability', 'growth', 'decision quality', 'development speed'],
    problems: [
      'loss of focus',
      'unclear strategy',
      'unnecessary bureaucracy',
      'weak communication',
      'gap between planning and results',
    ],
    processes: ['team workflow', 'process management', 'planning', 'company growth', 'decision making'],
    tools: ['analytics', 'system thinking', 'clear communication', 'planning', 'prioritization'],
  },

  it: {
    subjects: ['platform', 'interface', 'service', 'digital product', 'application', 'architecture'],
    contexts: ['user experience', 'interface data', 'product analytics', 'technical overview', 'user feedback'],
    results: ['stability', 'performance', 'usability', 'product quality', 'development speed'],
    problems: [
      'technical debt',
      'complex navigation',
      'unstable logic',
      'unnecessary complexity',
      'poor feedback loop',
    ],
    processes: ['development', 'interface design', 'testing', 'product improvement', 'architecture work'],
    tools: ['type safety', 'automation', 'design system', 'analytics', 'code review'],
  },

  art: {
    subjects: ['exhibition', 'gallery', 'visual style', 'creative project', 'composition', 'art object'],
    contexts: ['visual analysis', 'audience response', 'creative process', 'exhibition space', 'image development'],
    results: ['engagement', 'visual expression', 'viewer interest', 'image consistency', 'emotional impact'],
    problems: [
      'visual noise',
      'weak idea',
      'loss of attention',
      'unclear presentation',
      'gap between form and meaning',
    ],
    processes: ['composition work', 'image creation', 'exhibition planning', 'visual research', 'creative direction'],
    tools: ['composition', 'lighting', 'color', 'space', 'rhythm'],
  },

  science: {
    subjects: ['research', 'hypothesis', 'experiment', 'model', 'methodology', 'scientific approach'],
    contexts: ['data analysis', 'experiment results', 'research methodology', 'hypothesis testing', 'model comparison'],
    results: ['accuracy', 'reliability', 'repeatability', 'quality of conclusions', 'clarity of results'],
    problems: ['measurement errors', 'data bias', 'limited sample size', 'weak hypothesis', 'unclear methodology'],
    processes: ['data analysis', 'hypothesis testing', 'experiment design', 'result interpretation', 'model building'],
    tools: ['statistics', 'modeling', 'comparative analysis', 'experiment', 'data visualization'],
  },

  finance: {
    subjects: ['budget', 'financial model', 'reporting', 'cash flow', 'investment portfolio', 'financial plan'],
    contexts: ['expense analysis', 'financial forecast', 'cost structure', 'cash movement', 'risk assessment'],
    results: ['profitability', 'transparency', 'expense control', 'financial stability', 'forecast accuracy'],
    problems: ['cash gap', 'unclear reporting', 'growing costs', 'planning errors', 'loss of control'],
    processes: ['budgeting', 'financial planning', 'expense analysis', 'risk management', 'report preparation'],
    tools: ['forecasting', 'financial analytics', 'expense tracking', 'planning', 'metric control'],
  },

  marketing: {
    subjects: ['campaign', 'brand', 'audience', 'sales funnel', 'content strategy', 'positioning'],
    contexts: ['audience analysis', 'customer behavior', 'campaign data', 'touchpoint map', 'demand analysis'],
    results: ['conversion', 'brand awareness', 'loyalty', 'lead quality', 'communication efficiency'],
    problems: ['unclear positioning', 'low conversion', 'loss of attention', 'weak message', 'wrong segment'],
    processes: ['campaign launch', 'audience work', 'content creation', 'funnel setup', 'brand development'],
    tools: ['segmentation', 'analytics', 'content', 'positioning', 'hypothesis testing'],
  },
};
