import '../../shared/styles/index.css';

import { routing } from '@website/i18n/routing';
import { ThemeProvider } from '@website/shared/providers/theme-provider';
import { Layout } from '@website/shared/ui/Layout/Layout';
import { Header } from '@website/widgets/header';
import { notFound } from 'next/navigation';
import { hasLocale, NextIntlClientProvider } from 'next-intl';

export const metadata = {
  title: 'Lorema',
  description: 'Generated by create-nx-workspace',
};

type Props = {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
};

const RootLayout = async (props: Props) => {
  const { children, params } = props;
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <NextIntlClientProvider>
          <ThemeProvider>
            <Layout>
              <Header />
              <body>{children}</body>
            </Layout>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
