import { AddressFormat } from 'src/features/content-generation/model';
import { Language } from 'src/shared/model/types';

import { AddressParts } from '../model/types';

export const ADDRESS_PARTS_RU: AddressParts = {
  countries: ['Россия'],

  regions: [
    'Московская область',
    'Ленинградская область',
    'Самарская область',
    'Свердловская область',
    'Республика Татарстан',
    'Краснодарский край',
    'Пермский край',
    'Новосибирская область',
    'Нижегородская область',
    'Ростовская область',
    'Воронежская область',
    'Челябинская область',
    'Тюменская область',
    'Иркутская область',
    'Омская область',
    'Саратовская область',
    'Волгоградская область',
    'Ярославская область',
    'Калужская область',
    'Тульская область',
    'Рязанская область',
    'Владимирская область',
    'Республика Башкортостан',
    'Республика Карелия',
    'Приморский край',
    'Хабаровский край',
  ],

  states: [],

  cityTypes: ['г.', 'город'],

  cities: [
    'Москва',
    'Санкт-Петербург',
    'Самара',
    'Казань',
    'Екатеринбург',
    'Новосибирск',
    'Нижний Новгород',
    'Ростов-на-Дону',
    'Краснодар',
    'Пермь',
    'Ульяновск',
    'Воронеж',
    'Челябинск',
    'Уфа',
    'Омск',
    'Волгоград',
    'Саратов',
    'Тюмень',
    'Иркутск',
    'Ярославль',
    'Тула',
    'Рязань',
    'Калуга',
    'Владимир',
    'Тверь',
    'Киров',
    'Пенза',
    'Барнаул',
    'Томск',
    'Кемерово',
    'Ижевск',
    'Оренбург',
    'Астрахань',
    'Сочи',
    'Владивосток',
    'Хабаровск',
  ],

  streetTypes: ['ул.', 'улица', 'проспект', 'пр-т', 'пер.', 'переулок', 'бульвар', 'шоссе', 'площадь', 'проезд'],

  streetNames: [
    'Ленина',
    'Мира',
    'Советская',
    'Центральная',
    'Набережная',
    'Пушкина',
    'Гагарина',
    'Кирова',
    'Молодежная',
    'Садовая',
    'Лесная',
    'Зеленая',
    'Полевая',
    'Школьная',
    'Заводская',
    'Солнечная',
    'Новая',
    'Строителей',
    'Александра Невского',
    'Победы',
    'Октябрьская',
    'Первомайская',
    'Комсомольская',
    'Парковая',
    'Речная',
    'Березовая',
    'Южная',
    'Северная',
    'Восточная',
    'Западная',
    'Горького',
    'Чехова',
    'Толстого',
    'Достоевского',
    'Тургенева',
    'Некрасова',
    'Лермонтова',
    'Маяковского',
    'Есенина',
    'Королева',
    'Титова',
    'Жукова',
    'Космонавтов',
    'Металлургов',
    'Энергетиков',
    'Механизаторов',
    'Рабочая',
    'Индустриальная',
    'Вокзальная',
    'Спортивная',
    'Театральная',
    'Университетская',
    'Академическая',
    'Медицинская',
    'Почтовая',
    'Торговая',
    'Дружбы',
    'Свободы',
    '8 Марта',
    '9 Мая',
    '40 лет Победы',
    '50 лет Октября',
  ],
};

export const ADDRESS_PARTS_EN: AddressParts = {
  countries: ['USA'],

  regions: [],

  states: ['CA', 'NY', 'TX', 'FL', 'WA', 'IL', 'PA', 'OH', 'AZ', 'CO', 'MA', 'GA', 'NC', 'MI', 'NJ', 'VA', 'OR'],

  cityTypes: [],

  cities: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'Austin',
    'Jacksonville',
    'San Jose',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Boston',
    'Nashville',
    'Portland',
    'Las Vegas',
    'Detroit',
    'Miami',
    'Atlanta',
    'Orlando',
    'Tampa',
    'Sacramento',
    'Kansas City',
    'Cleveland',
  ],

  streetTypes: ['St', 'Ave', 'Blvd', 'Rd', 'Ln', 'Dr', 'Way', 'Ct', 'Pl'],

  streetNames: [
    'Main',
    'Oak',
    'Pine',
    'Maple',
    'Cedar',
    'Park',
    'Washington',
    'Lake',
    'Hill',
    'Sunset',
    'Highland',
    'Church',
    'River',
    'Lincoln',
    'Adams',
    'Madison',
    'Jefferson',
    'Franklin',
    'Broadway',
    'Forest',
    'Elm',
    'Walnut',
    'Cherry',
    'Willow',
    'Spruce',
    'Chestnut',
    'Dogwood',
    'Magnolia',
    'Meadow',
    'Ridge',
    'Valley',
    'Center',
    'Market',
    'Union',
    'King',
    'Queen',
    'Victoria',
    'George',
    'Oxford',
    'Cambridge',
    'Baker',
    'Mill',
    'Bridge',
    'Station',
    'College',
    'School',
    'Spring',
    'Summer',
    'Winter',
    'North',
    'South',
    'East',
    'West',
    'Hillside',
    'Riverside',
    'Lakeside',
    'Greenwood',
    'Fairview',
    'Woodland',
    'Brookfield',
  ],
};

export const ADDRESS_PARTS_BY_LANGUAGE: Record<Language, AddressParts> = {
  ru: ADDRESS_PARTS_RU,
  en: ADDRESS_PARTS_EN,
};

export const ADDRESS_FORMATS: AddressFormat[] = ['short', 'full', 'postal', 'legal'];
