export const CONTENT_FORM_FIELD_IDS = {
  textLengthInput: 'textLengthInput',
  textLengthError: 'textLengthError',
  titleLengthPresetSelect: 'titleLengthPresetSelect',
  emailLengthPresetSelect: 'emailLengthPresetSelect',
  linkLengthPresetSelect: 'linkLengthPresetSelect',
  linkPrefixSelect: 'linkPrefixSelect',
  phoneFormatSelect: 'phoneFormatSelect',
  countryCodeInput: 'countryCodeInput',
  digitsCountInput: 'digitsCountInput',
  countryCodeError: 'countryCodeError',
  digitsCountError: 'digitsCountError',
  paragraphsCheckbox: 'paragraphsCheckbox',
  keepWholeSentencies: 'keepWholeSentencies',
  addressFormatSelect: 'addressFormatSelect',
  firstNameLengthSelect: 'firstNameLengthSelect',
  lastNameLengthSelect: 'lastNameLengthSelect',
  topicSelect: 'topicSelect',
} as const;
