import { TextParts } from '../model/types';

export const TEXT_PARTS_RU: TextParts = {
  starts: [
    'рациональная организация процесса показывает, что',
    'системный подход демонстрирует, что',
    'переход к новым подходам подтверждает, что',
    'практика показывает, что',
    'в условиях активного роста',
    'анализ текущей ситуации свидетельствует о том, что',
    'опыт внедрения изменений показывает, что',
    'на фоне растущих требований',
    'на уровне повседневной практики',
    'с учётом практической пользы',
    'исходя из общепринятой практики,',
    'современная практика подтверждает, что',
    'накопленный опыт показывает, что',
    'анализ реальных процессов демонстрирует, что',
    'текущая ситуация свидетельствует о том, что',
    'практический опыт подтверждает, что',
    'многолетняя практика показывает, что',
    'результаты наблюдений указывают на то, что',
    'проведённый анализ позволяет утверждать, что',
    'имеющиеся данные подтверждают, что',
    'общая тенденция показывает, что',
    'в условиях высокой неопределённости',
    'в рамках современных требований',
    'в процессе дальнейшего развития',
    'в условиях постоянных изменений',
    'в условиях растущей конкуренции',
    'на фоне стремительного развития технологий',
    'в рамках выбранной стратегии',
    'при решении комплексных задач',
    'в ходе реализации намеченных планов',
    'в условиях ограниченных ресурсов',
    'в процессе цифровой трансформации',
    'в условиях динамично меняющейся среды',
    'важно отметить, что',
    'следует учитывать, что',
    'необходимо подчеркнуть, что',
    'можно с уверенностью сказать, что',
    'не вызывает сомнений, что',
    'следует признать, что',
    'стоит обратить внимание на то, что',
    'нельзя не отметить, что',
    'как показывает практика,',
    'как показывает накопленный опыт,',
    'с точки зрения долгосрочного развития',
    'в контексте поставленных целей',
    'в рамках системного подхода',
    'при комплексной оценке ситуации',
    'с позиции эффективного управления',
    'с учётом внешних факторов',
    'с учётом текущих обстоятельств',
    'при формировании устойчивой модели работы',
    'в рамках реализации стратегических инициатив',
    'в контексте современных вызовов',
    'на практике нередко оказывается, что',
    'в большинстве случаев становится очевидно, что',
    'со временем становится понятно, что',
    'при ближайшем рассмотрении видно, что',
    'как показывает повседневный опыт,',
    'при детальном анализе становится ясно, что',
    'в конечном итоге оказывается, что',
    'достаточно часто можно наблюдать, что',
  ],
  subjects: [
    'современные требования',
    'системные изменения',
    'новые методики',
    'актуальные подходы',
    'организационные решения',
    'управленческие практики',
    'технологические инновации',
    'социальные факторы',
    'операционные процессы',
    'организационные механизмы',
    'механизмы контроля',
    'качество взаимодействия',
    'ключевые процессы',
    'системные изменения',
    'практические решения',
    'организационные механизмы',
    'рабочие подходы',
    'стратегические инициативы',
    'текущие задачи',
    'основные направления развития',
    'внутренние процессы',
    'внешние обстоятельства',
    'профессиональные навыки',
    'информационные потоки',
    'управленческие решения',
    'пользовательские сценарии',
    'технологические инструменты',
    'аналитические данные',
    'методы оценки',
    'механизмы адаптации',
    'показатели эффективности',
    'цифровые решения',
    'социальные факторы',
    'образовательные практики',
    'рабочие процессы',
    'производственные задачи',
    'творческие подходы',
    'поведенческие модели',
    'аналитические инструменты',
    'современные требования',
    'прикладные методы',
    'долгосрочные цели',
    'операционные процессы',
    'механизмы контроля',
    'проектные решения',
    'практические инструменты',
    'комплексные задачи',
    'результаты наблюдений',
    'сформированные подходы',
  ],
  predicates: [
    'поддерживают',
    'обеспечивают',
    'формируют',
    'определяют',
    'выделяют',
    'стимулируют',
    'усиливают',
    'расширяют',
    'повышают',
    'снижают',
    'укрепляют',
    'программируют',
    'задают',
    'создают',
    'решают',
    'распределяют',
    'переопределяют',
    'регламентируют',
  ],
  // Винительный
  objects: [
    'эффективное взаимодействие между участниками',
    'реализацию ключевых инициатив',
    'устойчивое развитие системы',
    'последовательное улучшение процессов',
    'качественное управление изменениями',
    'стратегическое планирование на всех уровнях',
    'практическую ценность эффективного распределения ресурсов',
    'результативность при решении комплексных задач',
    'понимание достижения поставленных целей',
    'развитие профессиональных навыков',
    'основу для дальнейших изменений',
  ],
  // Родительный
  objectsGen: [
    'вероятности ошибок в управлении изменениями',
    'рискам при реализации проектов',
    'неопределённости в принятии решений',
    'издержкам на внедрение новых практик',
    'сложности адаптации к новым условиям',
    'стабильному функционированию процесса при необходимости точной координации',
  ],
  // Дательный
  objectsDat: [
    'развитию управленческих практик',
    'совершенствованию рабочих процессов',
    'улучшению системы взаимодействия',
    'внедрению инновационных подходов',
    'оптимизации ресурсов',
  ],
  // Предложный
  objectsLoc: [
    'управлении текущими изменениями',
    'процессе принятия решений',
    'реализации стратегических инициатив',
    'условиях быстрого роста',
    'организации рабочих процессов',
  ],
  endings: [
    'в условиях быстрого принятия решений.',
    'что особенно важно в современных условиях.',
    'в рамках текущих задач.',
    'на всех уровнях организации.',
    'при последовательном подходе.',
    'в долгосрочной перспективе.',
    'при решении комплексных задач.',
    'в рамках выбранной стратегии.',
    'в современных условиях.',
    'с учётом актуальных требований.',
    'на всех этапах работы.',
    'при активном развитии направления.',
    'в рамках выбранной стратегии.',
    'с опорой на практический опыт.',
    'при грамотной организации процесса.',
    'в условиях высокой нагрузки.',
    'при взаимодействии разных участников.',
    'на фоне постоянных изменений.',
    'в долгосрочной перспективе.',
    'при решении комплексных задач.',
    'с учётом внешних обстоятельств.',
    'в процессе ежедневной практики.',
    'для достижения устойчивого результата.',
    'при ограниченных ресурсах.',
    'в рамках системного подхода.',
    'при необходимости быстрой адаптации.',
    'в условиях растущей конкуренции.',
    'с учётом индивидуальных особенностей.',
    'при работе с большим объёмом информации.',
    'в процессе развития проекта.',
    'на уровне практического применения.',
    'при изменении исходных условий.',
    'при сохранении общей устойчивости.',
    'в условиях динамичного развития.',
    'в рамках долгосрочного планирования.',
    'с ориентацией на практический результат.',
    'при соблюдении ключевых принципов.',
    'в процессе дальнейшего совершенствования.',
    'на основе накопленного опыта.',
    'в условиях изменяющейся среды.',
    'при комплексном рассмотрении вопроса.',
    'с учётом долгосрочных целей.',
    'при эффективном распределении ресурсов.',
    'в контексте современных вызовов.',
    'на практике повседневной деятельности.',
    'при необходимости оперативного реагирования.',
    'в рамках устойчивого развития.',
    'при сохранении высокого уровня качества.',
    'с учётом специфики конкретной ситуации.',
    'при последовательной реализации намеченных планов.',
    'в условиях высокой степени ответственности.',
    'в рамках непрерывного совершенствования процессов.',
    'для достижения поставленных целей.',
    'для формирования устойчивого результата.',
    'для повышения общей эффективности.',
    'для обеспечения необходимого уровня качества.',
    'для поддержания стабильного развития.',
    'для успешной реализации намеченных инициатив.',
    'что позволяет достигать более предсказуемых результатов.',
    'что способствует повышению общей результативности.',
    'что создаёт дополнительные возможности для развития.',
    'что обеспечивает необходимую гибкость процессов.',
    'что помогает своевременно реагировать на изменения.',
    'что повышает устойчивость принимаемых решений.',
    'что делает процесс более прозрачным и понятным.',
    'что положительно влияет на конечный результат.',
    'что позволяет эффективнее использовать доступные ресурсы.',
    'что способствует формированию единого подхода.',
    'что создаёт условия для дальнейшего роста.',
    'что помогает сохранять баланс между задачами и ресурсами.',
    'что особенно актуально в условиях современных изменений.',
  ],
};

export const TEXT_PARTS_EN: TextParts = {
  starts: [
    'a rational approach to the process shows that',
    'a systematic perspective confirms that',
    'transitioning to new approaches demonstrates that',
    'experience shows that',
    'analysis of the current situation indicates that',
    'the practice of implementing changes shows that',
    'a review of current practices shows that',
    'accumulated experience confirms that',
    'current trends indicate that',
    'practical observations demonstrate that',
    'it is important to note that',
    'it should be taken into account that',
    'modern conditions require that',
    'careful analysis demonstrates that',
    'available data suggests that',
    'current developments confirm that',
    'in most cases it becomes clear that',
    'over time it becomes evident that',
  ],

  subjects: [
    'modern requirements',
    'systemic changes',
    'current approaches',
    'organizational decisions',
    'management practices',
    'technological innovations',
    'operational processes',
    'organizational mechanisms',
    'control mechanisms',
    'quality standards',
    'strategic initiatives',
    'internal processes',
    'analytical tools',
    'professional practices',
    'working methods',
  ],

  predicates: [
    'support',
    'strengthen',
    'improve',
    'expand',
    'reinforce',
    'ensure',
    'increase the value of',
    'create conditions for',
    'provide support for',
    'make it possible to improve',
  ],

  objects: [
    'effective interaction among participants',
    'the implementation of key initiatives',
    'sustainable system development',
    'consistent process improvement',
    'quality change management',
    'strategic planning at all levels',
    'efficient resource allocation',
    'performance in complex tasks',
    'the achievement of shared goals',
    'professional skill development',
    'the quality of decision-making',
    'the transparency of internal processes',
    'the practical value of new solutions',
  ],

  objectsGen: [
    'the likelihood of errors in change management',
    'the risks associated with project implementation',
    'uncertainty in decision-making',
    'the cost of adopting new practices',
    'the complexity of adapting to new conditions',
    'the pressure on operational processes',
    'the number of inconsistencies in workflow management',
    'the impact of external constraints',
  ],

  objectsDat: [
    'the development of management practices',
    'the improvement of workflows',
    'the enhancement of interaction systems',
    'the adoption of innovative approaches',
    'the optimization of available resources',
    'the formation of sustainable working models',
    'the implementation of long-term initiatives',
    'the improvement of organizational efficiency',
  ],

  objectsLoc: [
    'managing ongoing changes',
    'the decision-making process',
    'the implementation of strategic initiatives',
    'conditions of rapid growth',
    'the organization of workflows',
    'daily operational practice',
    'complex project environments',
    'long-term planning processes',
    'cross-functional collaboration',
  ],

  endings: [
    'in conditions of rapid decision-making.',
    'which is especially important in modern environments.',
    'within the scope of current tasks.',
    'at all levels of the organization.',
    'with a consistent approach.',
    'in the long run.',
    'when addressing complex challenges.',
    'within the chosen strategy.',
    'under conditions of continuous change.',
    'with consideration of current requirements.',
    'within the framework of sustainable development.',
    'in the context of long-term objectives.',
    'while maintaining overall stability.',
    'throughout the entire implementation process.',
    'with a focus on practical outcomes.',
    'when working with limited resources.',
    'while preserving operational efficiency.',
    'within a rapidly changing environment.',
    'with due consideration of external factors.',
    'through the effective use of available resources.',
    'with an emphasis on sustainable growth.',
    'while adapting to changing circumstances.',
    'through continuous process improvement.',
    'which contributes to greater overall efficiency.',
    'which creates additional opportunities for growth.',
    'which helps achieve more predictable outcomes.',
    'which supports long-term development.',
    'which improves the quality of decision-making.',
    'which enables a more flexible response to change.',
    'which helps ensure sustainable results.',
  ],
};

export const TEXT_PARTS_LA: TextParts = {
  starts: [
    'a rational approach to the process shows that',
    'a systematic perspective confirms that',
    'transitioning to new approaches demonstrates that',
    'experience shows that',
    'analysis of the current situation indicates that',
    'the practice of implementing changes shows that',
    'a review of current practices shows that',
    'accumulated experience confirms that',
    'current trends indicate that',
    'practical observations demonstrate that',
    'it is important to note that',
    'it should be taken into account that',
    'modern conditions require that',
    'careful analysis demonstrates that',
    'available data suggests that',
    'current developments confirm that',
    'in most cases it becomes clear that',
    'over time it becomes evident that',
  ],

  subjects: [
    'modern requirements',
    'systemic changes',
    'current approaches',
    'organizational decisions',
    'management practices',
    'technological innovations',
    'operational processes',
    'organizational mechanisms',
    'control mechanisms',
    'quality standards',
    'strategic initiatives',
    'internal processes',
    'analytical tools',
    'professional practices',
    'working methods',
  ],

  predicates: [
    'support',
    'strengthen',
    'improve',
    'expand',
    'reinforce',
    'ensure',
    'increase the value of',
    'create conditions for',
    'provide support for',
    'make it possible to improve',
  ],

  objects: [
    'effective interaction among participants',
    'the implementation of key initiatives',
    'sustainable system development',
    'consistent process improvement',
    'quality change management',
    'strategic planning at all levels',
    'efficient resource allocation',
    'performance in complex tasks',
    'the achievement of shared goals',
    'professional skill development',
    'the quality of decision-making',
    'the transparency of internal processes',
    'the practical value of new solutions',
  ],

  objectsGen: [
    'the likelihood of errors in change management',
    'the risks associated with project implementation',
    'uncertainty in decision-making',
    'the cost of adopting new practices',
    'the complexity of adapting to new conditions',
    'the pressure on operational processes',
    'the number of inconsistencies in workflow management',
    'the impact of external constraints',
  ],

  objectsDat: [
    'the development of management practices',
    'the improvement of workflows',
    'the enhancement of interaction systems',
    'the adoption of innovative approaches',
    'the optimization of available resources',
    'the formation of sustainable working models',
    'the implementation of long-term initiatives',
    'the improvement of organizational efficiency',
  ],

  objectsLoc: [
    'managing ongoing changes',
    'the decision-making process',
    'the implementation of strategic initiatives',
    'conditions of rapid growth',
    'the organization of workflows',
    'daily operational practice',
    'complex project environments',
    'long-term planning processes',
    'cross-functional collaboration',
  ],

  endings: [
    'in conditions of rapid decision-making.',
    'which is especially important in modern environments.',
    'within the scope of current tasks.',
    'at all levels of the organization.',
    'with a consistent approach.',
    'in the long run.',
    'when addressing complex challenges.',
    'within the chosen strategy.',
    'under conditions of continuous change.',
    'with consideration of current requirements.',
    'within the framework of sustainable development.',
    'in the context of long-term objectives.',
    'while maintaining overall stability.',
    'throughout the entire implementation process.',
    'with a focus on practical outcomes.',
    'when working with limited resources.',
    'while preserving operational efficiency.',
    'within a rapidly changing environment.',
    'with due consideration of external factors.',
    'through the effective use of available resources.',
    'with an emphasis on sustainable growth.',
    'while adapting to changing circumstances.',
    'through continuous process improvement.',
    'which contributes to greater overall efficiency.',
    'which creates additional opportunities for growth.',
    'which helps achieve more predictable outcomes.',
    'which supports long-term development.',
    'which improves the quality of decision-making.',
    'which enables a more flexible response to change.',
    'which helps ensure sustainable results.',
  ],
};
