import '../styles/global.css';

export const metadata = {
  title: 'Lorema',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = (props: { children: React.ReactNode }) => {
  const { children } = props;

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
