import { Language, NameLengthPreset, NameLengthSelectOption } from 'src/shared/model/types';

import { NameParts } from '../model/types';

export const NAME_LENGTH_PRESETS: NameLengthPreset[] = ['sm', 'md', 'lg'];
export const NAME_LENGTH_SELECT_OPTIONS: NameLengthSelectOption[] = ['random', ...NAME_LENGTH_PRESETS];

export const NAME_PARTS_RU: NameParts = {
  firstNames: {
    sm: ['Ян', 'Лев', 'Иван', 'Марк', 'Глеб', 'Анна', 'Яна', 'Ева', 'Алла', 'Инна', 'Лида'],
    md: ['Андрей', 'Михаил', 'Степан', 'Евгений', 'Сергей', 'Дмитрий', 'Николай', 'Марина', 'Наталья'],
    lg: ['Константин', 'Владислав', 'Святослав', 'Ростислав', 'Аполлинария', 'Александра', 'Елизавета'],
  },

  lastNames: {
    sm: ['Ли', 'Ким', 'Юн', 'Ван', 'Мун', 'Бек', 'Вольф', 'Шмидт', 'Хан', 'Чан', 'Лин', 'Тан', 'Фокс', 'Кейн'],
    md: [
      'Ригер',
      'Холмс',
      'Вебер',
      'Фишер',
      'Миллер',
      'Вагнер',
      'Крамер',
      'Лангер',
      'Штайнер',
      'Морган',
      'Кэмпбелл',
      'Баркер',
      'Картер',
      'Спенсер',
      'Фостер',
      'Тейлор',
      'Уолкер',
      'Портер',
      'Бауэр',
      'Келлер',
    ],
    lg: [
      'Айзенберг',
      'Розенфельд',
      'Вайнштейн',
      'Шнайдерман',
      'Хоэнштайн',
      'Шварценберг',
      'Фицджеральд',
      'Монтгомери',
      'Ливингстон',
      'Харрингтон',
      'Макаллистер',
      'Вандерберг',
      'Винтерштейн',
      'Шумахерман',
    ],
  },
};

export const NAME_PARTS_EN: NameParts = {
  firstNames: {
    sm: ['Ben', 'Tom', 'Max', 'Sam', 'Jack', 'Luke', 'John', 'Emma', 'Anna', 'Kate', 'Rose', 'Lily'],
    md: ['Michael', 'William', 'Richard', 'Charles', 'Matthew', 'Jessica', 'Sophia', 'Madison', 'Abigail'],
    lg: ['Alexander', 'Christopher', 'Nathaniel', 'Sebastian', 'Maximilian', 'Alexandria', 'Anastasia'],
  },

  lastNames: {
    sm: [
      'Smith',
      'Brown',
      'Jones',
      'Clark',
      'Hall',
      'Young',
      'White',
      'Stone',
      'King',
      'Wood',
      'Fox',
      'Lee',
      'Kim',
      'Khan',
    ],
    md: [
      'Anderson',
      'Robinson',
      'Mitchell',
      'Campbell',
      'Peterson',
      'Thompson',
      'Weber',
      'Fischer',
      'Muller',
      'Wagner',
      'Kramer',
      'Bauer',
      'Romano',
      'Ferrari',
      'Moretti',
      'Ricci',
      'Marino',
      'Conti',
      'Garcia',
      'Martinez',
      'Gonzalez',
      'Rodriguez',
      'Fernandez',
      'Ramirez',
      'Morales',
    ],
    lg: [
      'Montgomery',
      'Fitzgerald',
      'Livingston',
      'Winchester',
      'Washington',
      'Richardson',
      'Harrington',
      'Schwarzenberg',
      'Rosenfeld',
      'Eisenberg',
      'Winterstein',
      'Hohenstein',
      'Michelangelo',
      'Castellucci',
      'Santangelo',
      'Belladonna',
      'Bartolomeo',
      'Villanueva',
      'Montenegro',
      'Castellanos',
      'Valderrama',
      'Bustamante',
      'Guadarrama',
    ],
  },
};

export const NAME_PARTS_BY_LANGUAGE: Record<Language, NameParts> = {
  ru: NAME_PARTS_RU,
  en: NAME_PARTS_EN,
};
